---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: Astra Tridentのアンインストールには、Astra Tridentのインストールと同じ方法を使用する必要があります。アップグレード、依存関係の問題、アップグレードの失敗や不完全な完了後に見つかったバグを修正する必要がある場合は、Astra Tridentをアンインストールし、そのバージョンに固有の手順を使用して以前のバージョンを再インストールする必要があります。 
---
= Astra Trident をアンインストール
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Tridentのアンインストールには、Astra Tridentのインストールと同じ方法を使用する必要があります。

.タスクの内容
* アップグレード、依存関係の問題、アップグレードの失敗または不完全な完了後に見つかったバグの修正が必要な場合は、Astra Tridentをアンインストールし、該当する手順を使用して以前のバージョンを再インストールする必要がありますlink:../earlier-versions.html["バージョン"]。これは、以前のバージョンに_downgrade_toを実行するための唯一の推奨方法です。
* アップグレードと再インストールを簡単に行うため、Astra Tridentをアンインストールしても、Astra Tridentで作成されたCRDや関連オブジェクトは削除されません。Astra Tridentとそのすべてのデータを完全に削除する必要がある場合は、を参照してくださいlink:../troubleshooting.html#completely-remove-astra-trident-and-crds["Astra TridentとCRDを完全に削除"]。


.開始する前に
Kubernetesクラスタの運用を停止する場合は、Astra Tridentで作成されたボリュームを使用するすべてのアプリケーションをアンインストールする前に削除する必要があります。これにより、PVCが削除される前にKubernetesノードで非公開になります。



== 元のインストール方法を決定する

Astra Tridentは、インストール時と同じ方法でアンインストールする必要があります。アンインストールする前に、Astra Tridentの最初のインストールに使用したバージョンを確認します。

. ポッドの検査に使用し `kubectl get pods -n trident`ます。
+
** オペレータポッドがない場合は、を使用してAstra Tridentをインストールしました `tridentctl`。
** オペレータポッドがある場合、Astra Tridentは手動またはHelmを使用してインストールされています。


. オペレータポッドがある場合は、を使用 `kubectl describe tproc trident`してAstra TridentがHelmを使用してインストールされているかどうかを確認します。
+
** Helmラベルがある場合は、Helmを使用してAstra Tridentがインストールされています。
** Helmラベルがない場合は、Astra TridentをTridentオペレータを使用して手動でインストールしています。






== Tridentオペレータのインストールをアンインストールする

Tridentオペレータのインストールは手動でアンインストールすることも、Helmを使用してアンインストールすることもできます。



=== 手動インストールのアンインストール

オペレータを使用してAstra Tridentをインストールした場合は、次のいずれかの方法でアンインストールできます。

. ** CRを編集し `TridentOrchestrator`てアンインストールフラグを設定**：
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
+
フラグがに設定されて `true`いる場合、 `uninstall`TridentオペレータはTridentをアンインストールしますが、TridentOrchestrator自体は削除しません。Trident を再度インストールする場合は、 TridentOrchestrator をクリーンアップして新しい Trident を作成する必要があります。

. **削除 `TridentOrchestrator`**：Astra Tridentの導入に使用したCRを削除することで `TridentOrchestrator`、オペレータにTridentをアンインストールするよう指示します。オペレータがの削除処理を行い `TridentOrchestrator`、Astra Tridentの導入とデーモンセットの削除に進み、インストール時に作成したTridentポッドが削除されます。
+
[listing]
----
kubectl delete -f deploy/<bundle.yaml> -n <namespace>
----




=== Helmインストールのアンインストール

Helmを使用してAstra Tridentをインストールした場合は、を使用してアンインストールできます `helm uninstall`。

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== インストールのアンインストール `tridentctl`

CRDと関連オブジェクトを除くAstra Tridentに関連付けられているすべてのリソースを削除するには、のコマンドを `tridentctl`使用し `uninstall`ます。

[listing]
----
./tridentctl uninstall -n <namespace>
----