---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 既存の Astra Trident インストールは、オペレータが簡単にアップグレードできます。 
---
= Trident OperatorまたはHelmを使用してAstra Tridentのインストールをアップグレード
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Tridentは、Tridentオペレータを使用して手動またはHelmを使用してアップグレードできます。Tridentオペレータのインストールから別のTridentオペレータのインストールにアップグレードすることも、インストールからTridentオペレータのバージョンにアップグレードすることもできます `tridentctl`。Trident Operatorのインストールをアップグレードする前にを参照してくださいlink:upgrade-trident.html#select-an-upgrade-method["アップグレード方法を選択します"]。



== 手動インストールのアップグレード

クラスタを対象としたTridentオペレータインストールから、クラスタを対象とした別のTridentオペレータインストールにアップグレードできます。すべてのAstra Tridentバージョン21.01以降では、クラスタを対象とした演算子を使用します。


NOTE: ネームスペースを対象としたオペレータ（バージョン20.07~20.10）を使用してインストールされたAstra Tridentからアップグレードするには、Astra Tridentのアップグレード手順を使用しますlink:../earlier-versions.html["インストールされているバージョン"]。

.タスクの内容
Tridentにはバンドルファイルが用意されています。このファイルを使用して、オペレータをインストールしたり、Kubernetesバージョンに対応する関連オブジェクトを作成したりできます。

* クラスタでKubernetes 1.24を実行している場合は、を使用し link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_pre_1_25.yaml["Bundle_pre_1_25.yaml"^]ます。
* クラスタでKubernetes 1.25以降を実行している場合は、を使用します link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_post_1_25.yaml["bundle_post_1_25.yaml"^]。


.開始する前に
を実行しているKubernetesクラスタを使用していることを確認しlink:../trident-get-started/requirements.html["サポートされるKubernetesバージョン"]ます。

.手順
. Astra Tridentのバージョンを確認します。
+
[listing]
----
./tridentctl -n trident version
----
. 現在の Astra Trident インスタンスのインストールに使用した Trident オペレータを削除たとえば、23.07からアップグレードする場合は、次のコマンドを実行します。
+
[listing]
----
kubectl delete -f 23.07.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. 属性を使用して初期インストールをカスタマイズした場合 `TridentOrchestrator`は、オブジェクトを編集してインストールパラメータを変更できます `TridentOrchestrator`。これには、ミラーリングされたTridentおよびCSIイメージレジストリをオフラインモードに指定したり、デバッグログを有効にしたり、イメージプルシークレットを指定したりするための変更が含まれます。
. 環境に適したバンドルYAMLファイルを使用してAstra Tridentをインストールします（_YAMLは、または使用している<bundle.yaml>
`bundle_pre_1_25.yaml` `bundle_post_1_25.yaml` のバージョンに基づいています）。たとえば、Astra Trident 24.06をインストールする場合は、次のコマンドを実行します。
+
[listing]
----
kubectl create -f 24.06.0/trident-installer/deploy/<bundle.yaml> -n trident
----




== Helmインストールのアップグレード

Astra Trident Helmのインストールをアップグレードできます。


WARNING: Astra TridentがインストールされているKubernetesクラスタを1.24から1.25以降にアップグレードする場合は `helm upgrade`、クラスタをアップグレードする前に、値.yamlをに `true`設定するかコマンドに追加するよう `--set excludePodSecurityPolicy=true`に更新する必要があります。 `excludePodSecurityPolicy`

.手順
. を使用する link:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-astra-trident-using-helm["Helmを使用したAstra Tridentのインストール"]と、を使用してワンステップでアップグレードできます `helm upgrade trident netapp-trident/trident-operator --version 100.2406.0` 。Helmリポジトリを追加しなかった場合、またはHelmリポジトリを使用してアップグレードできない場合は、次の手順を実行します。
+
.. から最新のAstra Tridentリリースをダウンロードしlink:https://github.com/NetApp/trident/releases/latest["GitHubの_Assets_sectionを参照してください"^]ます。
.. コマンドを使用し `helm upgrade` ます。は、 `trident-operator-24.06.0.tgz` アップグレード先のバージョンを反映しています。
+
[listing]
----
helm upgrade <name> trident-operator-24.06.0.tgz
----
+

NOTE: 初期インストール時にカスタムオプションを設定した場合（TridentおよびCSIイメージのプライベートなミラーレジストリの指定など）は、を使用してコマンドを追加し `helm upgrade`、これらのオプションがアップグレードコマンドに含まれていることを確認します。含まれていない場合は、 `--set`値がデフォルトにリセットされます。



. を実行し `helm list`て、チャートとアプリのバージョンの両方がアップグレードされたことを確認します。を実行し `tridentctl logs`てデバッグメッセージを確認します。




== インストールからTrident Operatorへのアップグレード `tridentctl`

インストールからTrident Operatorを最新リリースにアップグレードできます `tridentctl`。既存のバックエンドとPVCは自動的に使用可能になります。


NOTE: インストール方法を切り替える前に、を参照してくださいlink:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["インストール方法を切り替える"]。

.手順
. 最新の Astra Trident リリースをダウンロード
+
[listing]
----
# Download the release required [24.060.0]
mkdir 24.06.0
cd 24.06.0
wget https://github.com/NetApp/trident/releases/download/v24.06.0/trident-installer-24.06.0.tar.gz
tar -xf trident-installer-24.06.0.tar.gz
cd trident-installer
----
. マニフェストからCRDを作成し `tridentorchestrator`ます。
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. クラスタを対象としたオペレータを同じネームスペースに導入します。
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Astra TridentをインストールするためのCRを作成します `TridentOrchestrator`。
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Tridentが目的のバージョンにアップグレードされたことを確認
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v24.06.0
----

