---
sidebar: sidebar 
permalink: trident-use/anf.html 
keywords: trident backend, azure netapp files, smb volumes, smb, windows, drivers, access modes, rwo, rwx, rwp, rwop, file system, aks, managed identities, azure 
summary: Azure NetApp FilesはAstra Tridentのバックエンドとして設定できます。Azure NetApp Filesバックエンドを使用してNFSボリュームとSMBボリュームを接続できます。Astra Tridentでは、Azure Kubernetes Services（AKS）クラスタの管理対象IDを使用したクレデンシャル管理もサポートされます。 
---
= Azure NetApp Files バックエンドを設定します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Azure NetApp FilesはAstra Tridentのバックエンドとして設定できます。Azure NetApp Filesバックエンドを使用してNFSボリュームとSMBボリュームを接続できます。Astra Tridentでは、Azure Kubernetes Services（AKS）クラスタの管理対象IDを使用したクレデンシャル管理もサポートされます。



== Azure NetApp Filesドライバの詳細

Astra Tridentは、次のAzure NetApp Filesストレージドライバを使用してクラスタと通信します。サポートされているアクセスモードは、_ReadWriteOnce_(RWO)、_ReadOnlyMany_(ROX)、_ReadWriteMany_(RWX)、_ReadWriteOncePod_(RWOP)です。

[cols="2, 1, 1, 2, 2"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされるファイルシステム 


| `azure-netapp-files`  a| 
NFS SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
`nfs`、 `smb`

|===


=== 考慮事項

* Azure NetApp Files サービスでは、100GB未満のボリュームはサポートされません。容量の小さいボリュームが要求されると、Astra Tridentによって自動的に100GiBのボリュームが作成されます。
* Astra Tridentは、Windowsノードで実行されているポッドにマウントされたSMBボリュームのみをサポート




== AKSの管理対象ID

Astra TridentはAzure Kubernetes Servicesクラスタでサポートされますlink:https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview["管理対象ID"^]。管理されたアイデンティティによって提供される合理的なクレデンシャル管理を利用するには、次のものが必要です。

* AKSを使用して導入されるKubernetesクラスタ
* AKS Kubernetesクラスタに設定された管理対象ID
* 指定する `"Azure"`を含むAstra Tridentがインストールされます `cloudProvider`。
+
[role="tabbed-block"]
====
.Trident オペレータ
--
Tridentオペレータを使用してAstra Tridentをインストールするには、を編集し `tridentorchestrator_cr.yaml`てに設定します `cloudProvider` `"Azure"`。例：

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
----
--
.Helm
--
次の例では、環境変数を使用してAstra TridentセットをAzureに `$CP`インストールし `cloudProvider`ます。

[listing]
----
helm install trident trident-operator-100.2406.0.tgz --create-namespace --namespace <trident-namespace> --set cloudProvider=$CP
----
--
.<code> tridentctl </code>
--
次の例では、Astra Tridentをインストールし、フラグをに `Azure`設定してい `cloudProvider`ます。

[listing]
----
tridentctl install --cloud-provider="Azure" -n trident
----
--
====




== AKSのクラウドID

クラウドIDを使用すると、Kubernetesポッドは、明示的なAzureクレデンシャルを指定するのではなく、ワークロードIDとして認証することでAzureリソースにアクセスできます。

AzureでクラウドIDを活用するには、以下が必要です。

* AKSを使用して導入されるKubernetesクラスタ
* AKS Kubernetesクラスタに設定されたワークロードIDとoidc-issuer
* ワークロードIDを指定し `"Azure"`て `cloudIdentity`指定するを含むAstra Tridentをインストール `cloudProvider`
+
[role="tabbed-block"]
====
.Trident オペレータ
--
Tridentオペレータを使用してAstra Tridentをインストールするには、を編集し `tridentorchestrator_cr.yaml`て、をに `"Azure"`設定 `cloudProvider`し `cloudIdentity` `azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx`ます。

例：

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullPolicy: IfNotPresent
  cloudProvider: "Azure"
  *cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'*
----
--
.Helm
--
次の環境変数を使用して、* cloud-provider（CP）*フラグと* cloud-identity（CI）*フラグの値を設定します。

`export CP="Azure"`
`export CI="azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"`

次の例では、Astra Tridentをインストールし、環境変数を使用してをAzureに `$CP`設定し `cloudProvider`、を使用して環境変数を `$CI`設定してい `cloudIdentity`ます。

[listing]
----
helm install trident trident-operator-100.2406.0.tgz --set cloudProvider=$CP --set cloudIdentity=$CI
----
--
.<code> tridentctl </code>
--
次の環境変数を使用して、* cloud provider *フラグと* cloud identity *フラグの値を設定します。

`export CP="Azure"`
`export CI="azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"`

次の例では、Astra Tridentをインストールし、フラグを `$CP`、 `cloud-identity`に `$CI`設定してい `cloud-provider`ます。

[listing]
----
tridentctl install --cloud-provider=$CP --cloud-identity="$CI" -n trident
----
--
====

