---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP NAS ドライバを使用した ONTAP バックエンドの設定について説明します。 
---
= ONTAP NASドライバの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP および Cloud Volumes ONTAP の NAS ドライバを使用した ONTAP バックエンドの設定について説明します。



== ONTAP NASドライバの詳細

Astra Tridentは、ONTAPクラスタと通信するための次のNASストレージドライバを提供します。サポートされているアクセスモードは、_ReadWriteOnce_(RWO)、_ReadOnlyMany_(ROX)、_ReadWriteMany_(RWX)、_ReadWriteOncePod_(RWOP)です。


IMPORTANT: 保護、リカバリ、モビリティにAstra Controlを使用している場合は、を参照してください。<<Astra Controlドライバの互換性>>

[cols="2, 1, 1, 2, 2"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされるファイルシステム 


| `ontap-nas`  a| 
NFS SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs` `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs` `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
ファイルシステム
 a| 
RWO、ROX、RWX、RWOP
 a| 
""、 `nfs` `smb`

|===


=== Astra Controlドライバの互換性

Astra Controlは、 `ontap-nas-flexgroup`、、および `ontap-san`ドライバで作成されたボリュームに対して、シームレスな保護、ディザスタリカバリ、モビリティ（Kubernetesクラスタ間でのボリューム移動）を提供します `ontap-nas`。詳細については、を参照してください link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Controlレプリケーションの前提条件"^] 。

[WARNING]
====
* 永続的ボリュームの使用数がよりも多くなると予想される場合にのみ使用します `ontap-san-economy`link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^]。
* 永続的ボリュームの使用数がよりも多いと予想され、 `ontap-san-economy`ドライバを使用できない場合にのみlink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^]使用して `ontap-nas-economy`ください。
* データ保護、ディザスタリカバリ、モビリティの必要性が予想される場合は使用しない `ontap-nas-economy`でください。


====


== ユーザ権限

Astra Tridentは、ONTAP管理者またはSVM管理者（通常はクラスタユーザまたは `vsadmin`SVMユーザ、または同じロールの別の名前のユーザを使用）として実行することを想定しています `admin`。

Amazon FSx for NetApp ONTAP環境の場合、Astra Tridentは、クラスタユーザまたは `vsadmin`SVMユーザ、または同じロールの別の名前のユーザを使用して、ONTAP管理者またはSVM管理者として実行されることが想定され `fsxadmin`ます。この `fsxadmin`ユーザは、クラスタ管理者ユーザに代わる限定的なユーザです。


NOTE: パラメータを使用する場合は `limitAggregateUsage`、クラスタ管理者の権限が必要です。Amazon FSx for NetApp ONTAPとAstra Tridentを併用する場合、 `limitAggregateUsage`パラメータはユーザアカウントと `fsxadmin`ユーザアカウントでは機能しません `vsadmin`。このパラメータを指定すると設定処理は失敗します。

ONTAP内でTridentドライバが使用できる、より制限の厳しいロールを作成することは可能ですが、推奨しません。Trident の新リリースでは、多くの場合、考慮すべき API が追加で必要になるため、アップグレードが難しく、エラーも起こりやすくなります。
