---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: Astra TridentとAmazon FSx for NetApp ONTAP を使用すると、Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタで、ONTAP を基盤とするブロックおよびファイルの永続ボリュームをプロビジョニングできるようになります。 
---
= Amazon FSX for NetApp ONTAP で Astra Trident を使用
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP 対応の Amazon FSX"^]は、NetApp ONTAPストレージオペレーティングシステムを基盤とするファイルシステムを起動して実行できる、フルマネージドのAWSサービスです。FSX for ONTAP を使用すると、使い慣れたネットアップの機能、パフォーマンス、管理機能を活用しながら、AWSにデータを格納するためのシンプルさ、即応性、セキュリティ、拡張性を活用できます。FSX for ONTAP は、ONTAP ファイルシステムの機能と管理APIをサポートしています。

Amazon Elastic Kubernetes Service（EKS）で実行されているKubernetesクラスタが、ONTAP によってサポートされるブロックおよびファイルの永続ボリュームをプロビジョニングできるように、Amazon ONTAP ファイルシステム用のAmazon FSXをAstra Tridentに統合することができます。

ファイルシステムは、オンプレミスの ONTAP クラスタに似た、 Amazon FSX のプライマリリソースです。各 SVM 内には、ファイルとフォルダをファイルシステムに格納するデータコンテナである 1 つ以上のボリュームを作成できます。Amazon FSX for NetApp ONTAP を使用すると、 Data ONTAP はクラウド内の管理対象ファイルシステムとして提供されます。新しいファイルシステムのタイプは * NetApp ONTAP * です。

Amazon Elastic Kubernetes Service （ EKS ）で実行されている Astra Trident と Amazon FSX for NetApp ONTAP を使用すると、 ONTAP がサポートするブロックボリュームとファイル永続ボリュームを確実にプロビジョニングできます。



== 要件

link:../trident-get-started/requirements.html["Astra Trident の要件"]FSx for ONTAPとAstra Tridentを統合するには、さらに次のものが必要です。

* 既存のAmazon EKSクラスタまたはがインストールされた自己管理型Kubernetesクラスタ `kubectl`。
* クラスタのワーカーノードから到達可能な既存のAmazon FSx for NetApp ONTAPファイルシステムおよびStorage Virtual Machine（SVM）。
* 用に準備されたワーカーノードlink:worker-node-prep.html["NFSまたはiSCSI"]。
+

NOTE: EKS AMIタイプに応じて、Amazon LinuxおよびUbuntu（AMIS）で必要なノードの準備手順に従って https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine Images の略"^]ください。





== 考慮事項

* SMBボリューム：
+
** SMBボリュームはドライバのみを使用してサポートされ `ontap-nas`ます。
** SMBボリュームはAstra Trident EKSアドオンではサポートされません。
** Astra Tridentは、Windowsノードで実行されているポッドにマウントされたSMBボリュームのみをサポート詳細については、を参照してください link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["SMBボリュームをプロビジョニングする準備をします"] 。


* Astra Trident 24.02より前のバージョンでは、自動バックアップが有効になっているAmazon FSxファイルシステム上に作成されたボリュームはTridentで削除できませんでした。Astra Trident 24.02以降でこの問題を回避するには、AWS FSx for ONTAPのバックエンド構成ファイルで、AWS `apiRegion`、AWS、およびAWS `apikey`を `secretKey`指定し `fsxFilesystemID`ます。
+

NOTE: Astra Tridentに対してIAMロールを指定する場合は、、 `apiKey`の `secretKey`各フィールドをAstra Tridentに対して明示的に指定する必要はありません `apiRegion`。詳細については、を参照してください link:../trident-use/trident-fsx-examples.html["FSX（ONTAP の構成オプションと例）"]。





== 認証

Astra Tridentは、2種類の認証モードを提供します。

* クレデンシャルベース（推奨）：クレデンシャルをAWS Secrets Managerに安全に格納します。ファイルシステムのユーザ、またはSVM用に設定されているユーザを使用できます `fsxadmin` `vsadmin` 。
+

WARNING: Astra Tridentは、SVMユーザ、または別の名前で同じロールのユーザとして実行する必要があります `vsadmin`。Amazon FSx for NetApp ONTAPには、ONTAPクラスタユーザに代わる限定的なユーザが `admin`い `fsxadmin`ます。Astra Tridentでの使用を強く推奨します `vsadmin`。

* 証明書ベース： Astra Trident は、 SVM にインストールされている証明書を使用して、 FSX ファイルシステムの SVM と通信します。


認証を有効にする方法の詳細については、使用しているドライバタイプの認証を参照してください。

* link:ontap-nas-prep.html["ONTAP NAS認証"]
* link:ontap-san-prep.html["ONTAP SAN認証"]




== 詳細情報

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for NetApp ONTAP のドキュメント"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["Amazon FSX for NetApp ONTAP に関するブログ記事です"^]

