---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, tridentctl, windows 
summary: 'を使用してAstra Tridentをインストールでき `tridentctl`ます。このプロセスでは、Astra Tridentで必要なコンテナイメージがプライベートレジストリに格納されているかどうかに関係なく、環境 のインストールを実行します。' 
---
= tridentctlを使用してインストールします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
を使用してAstra Tridentをインストールでき `tridentctl`ます。このプロセスでは、Astra Tridentで必要なコンテナイメージがプライベートレジストリに格納されているかどうかに関係なく、環境 のインストールを実行します。配置をカスタマイズするには `tridentctl`、を参照してくださいlink:kubernetes-customize-deploy-tridentctl.html["tridentctl 展開をカスタマイズします"]。



== Astra Tridentに関する重要な情報24.06

* Astra Tridentに関する次の重要な情報をお読みください。*

.<strong> ：Trident </strong> に関する重要な情報
[%collapsible%open]
====
* TridentでKubernetes 1.27がサポートされるようになりました。Kubernetesをアップグレードする前にTridentをアップグレード
* Astra Tridentでは、SAN環境でのマルチパス構成の使用が厳密に実施されます。multipath.confファイルの推奨値はです `find_multipaths: no`。
+
マルチパス以外の構成を使用するか、multipath.confファイルにまたは `find_multipaths: smart`の値を使用する `find_multipaths: yes`と、マウントが失敗します。Tridentでは、21.07リリース以降での使用を推奨してい `find_multipaths: no`ます。



====


== 以下を使用してAstra Tridentをインストール `tridentctl`

link:../trident-get-started/kubernetes-deploy.html["インストールの概要"]インストールの前提条件を満たしていることを確認し、環境に適したインストールオプションを選択してください。

.開始する前に
インストールを開始する前に、Linuxホストにログインし、動作中のを管理していること、および必要なPrivilegesが揃っていることを確認しlink:requirements.html["サポートされる Kubernetes クラスタ"^]ます。


NOTE: OpenShiftでは、以降のすべての例での代わり `kubectl`にを使用し、または `oc login -u kube-admin`を `oc`実行して最初に* system:admin *としてログインし `oc login -u system:admin`ます。

[%collapsible%open]
====
. Kubernetesのバージョンを確認します。
+
[listing]
----
kubectl version
----
. クラスタ管理者の権限を確認します。
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Docker Hubのイメージを使用してポッドを起動し、ポッドネットワーク経由でストレージシステムにアクセスできることを確認します。
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== 手順1：Tridentのインストーラパッケージをダウンロード

Astra Tridentインストーラパッケージは、Tridentポッドを作成し、そのステートを維持するために使用されるCRDオブジェクトを設定し、CSIサイドカーを初期化して、プロビジョニングやクラスタホストへのボリュームの接続などのアクションを実行します。からTridentインストーラの最新バージョンをダウンロードして展開しlink:https://github.com/NetApp/trident/releases/latest["GitHubの_Assets_sectionを参照してください"^]ます。例では、選択した<trident-installer-XX.XX.X.tar.gz> Tridentバージョンを使用してupdate_Tridentを更新します。

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v24.06.0/trident-installer-24.06.0.tar.gz
tar -xf trident-installer-24.06.0.tar.gz
cd trident-installer
----


== 手順2：Astra Tridentをインストールする

コマンドを実行して、目的のネームスペースにAstra Tridentをインストールします `tridentctl install`。追加の引数を追加して、イメージのレジストリの場所を指定できます。

[role="tabbed-block"]
====
.標準モード
--
[listing]
----
./tridentctl install -n trident
----
--
.1つのレジストリ内のイメージ
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:24.06 --trident-image <your-registry>/trident:24.06.0
----
--
.異なるレジストリ内の画像
--
別のレジストリの場所を使用するには、をに `imageRegistry`追加する必要があります `sig-storage`。

[listing]
----
./tridentctl install -n trident --image-registry <your-registry>/sig-storage --autosupport-image <your-registry>/netapp/trident-autosupport:24.06 --trident-image <your-registry>/netapp/trident:24.06.0
----
--
====
インストールステータスは次のようになります。

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=24.06.0
INFO Trident installation succeeded.
....
----


== インストールの確認

ポッドの作成ステータスまたはを使用してインストールを確認できます `tridentctl`。



=== ポッドの作成ステータスを使用する

作成したポッドのステータスを確認することで、Astra Tridentのインストールが完了したかどうかを確認できます。

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: インストーラーが正常に完了しない場合、または (`trident-csi-<generated id>`23.01より前のバージョンでは* Running *ステータスがない場合、 `trident-controller-<generated id>`プラットフォームはインストールされていません。を使用し `-d` link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["デバッグモードをオンにします"]て、問題のトラブルシューティングを行います。



=== 使用方法 `tridentctl`

を使用して、インストールされているAstra Tridentのバージョンを確認できます `tridentctl`。

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 24.06.0        | 24.06.0        |
+----------------+----------------+
----


== 構成例

次の例は、を使用してAstra Tridentをインストールするための設定例 `tridentctl`です。

.Windowsノオト
[%collapsible]
====
WindowsノードでAstra Tridentを実行できるようにするには、次の手順を実行します。

[listing]
----
tridentctl install --windows -n trident
----
====
.強制的に切り離し
[%collapsible]
====
強制切り離しの詳細については、を参照してくださいlink:..trident-get-started/kubernetes-customize-deploy.html["Tridentオペレータのインストールをカスタマイズ"]。

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====