---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm, attributes, customize 
summary: Astra Tridentインストーラを使用して、導入をカスタマイズできます。 
---
= tridentctlのインストールをカスタマイズします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Tridentインストーラを使用して、インストールをカスタマイズできます。



== インストーラの詳細を確認してください

Astra Tridentインストーラを使用して、属性をカスタマイズできます。たとえば、Tridentイメージをプライベートリポジトリにコピーした場合は、を使用してイメージ名を指定できます `--trident-image`。Tridentイメージと必要なCSIサイドカーイメージをプライベートリポジトリにコピーした場合は、次の形式のスイッチを使用してリポジトリの場所を指定することをお勧めし `--image-registry`ます。 `<registry FQDN>[:port]`

Kubernetesのディストリビューションを使用していて、でデータが通常以外のパスに保持される `/var/lib/kubelet`場合は `kubelet`、を使用して代替パスを指定できます `--kubelet-dir`。

インストーラの引数で許可される範囲を超えてインストールをカスタマイズする必要がある場合は、配置ファイルをカスタマイズすることもできます。パラメータを使用する `--generate-custom-yaml`と、インストーラのディレクトリに次のYAMLファイルが作成され `setup`ます。

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml`


これらのファイルを生成したら、必要に応じてファイルを変更し、を使用してカスタム配置をインストールできます `--use-custom-yaml`。

[listing]
----
./tridentctl install -n trident --use-custom-yaml
----